### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [aleksandrKrylov/aleksandrKrylov.github.io#1]
Добрый вечер. Благодарю за проделанную работу.
К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать ее на данной итерации:

## Репозиторий
**Можно лучше**: Добавить .gitignore.
.gitignore должен содержать правила, исключающие попадание временных и\или системных файлов в репозиторий.
В случае если вы затрудняетесь с составлением списка базовых правил можете воспользоваться сервисом-генератором, например gitignore.io

## Регулярные выражения
**Можно лучше** Квантификатор `{,1}` можно не использовать. Он не играет никакой роли.

### Имя
**Нужно исправить** Нет ограничений на ввод значений в поле "Имя".
Ожидается, что будет установлено минимальное количество символов равное 2, а максимальное - 20.
Чтобы добавить необходимо использовать атрибуты:
minlength,
maxlength

### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`t2e-s_t@g-m2ail.academy` - адрес может содержать длинную доменную зону. Я рекомендую убрать ограничение на длину доменной зоны сверху

**Нужно исправить** следующие некорректные кейсы проходят валидацию
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`my---mail@site.ru` - адрес электронной почты, содержащий несколько символов '-' подряд является некорректным

### Адрес сайта
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`http://some.test.yandex.ru` - адрес сайта может включать в себя произвольное число поддоменов

**Можно лучше** следующие некорректные кейсы проходят валидацию
`http://www.google.ru///////` - в пути количество слешей подряд должно быть ограничено 1

**Comment by zlocate** [comment]
В процессе правок сломались кейсы описанные ниже
### Email
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`x@gmail.com` - имя пользователя может состоять из одного символа
`t2e-s_t@g-m2ail.academy` - имя пользователя может включать в себя одиночные подряд спецсимволы

### Адрес сайта
**Нужно исправить** следующие корректные кейсы не проходят валидацию
http://my-next-site.ru
http://x.com:30

**Comment by zlocate** [comment]
Список тест-кейсов для самопроверки:
Email
```
Позитивные:
some2@2domains.ru - имя и домен могут содержать цифры
som-e@d-omains.ru - имя и домен могут содержать тире
some@x.com - доменное имя может состоять из одного символа
x@gmail.com - имя ящика может состоять из одного символа
t2e-s_t@g-m2ail.academy
some@mail.yandex.ru
some-extra-long-name@some.extra.long.domain.name

Негативные:
_@site.ru - имя ящика не может состоять только из спецсимволов
_some_@ya.ru - имя ящика не может начинаться и заканчиваться на спецсимвол
my---mail@site.ru - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным
мояпочта@site.ru - имя ящика не может содержать кириллицу
-------------------@gmail.com
Hungry_developer22@яндекс.com (доменное имя или адрес не могут содержать кирилицу)
@gmail.com - адрес электронной почты должен содержать имя пользователя (название)
test@.
test@.com
m#i#e@gmail.com
```

Адрес сайта
```
Позитивные кейсы: (только не привязывайтесь к конкретным IP и доменам, я использую при проверке произвольные но соответствующие по сути)
http://ya.ru
https://www.ya.ru
http://google.ru:98/
http://x.com:30
http://google.ru/path/to/deep/
http://my-next-site.ru
http://8.8.8.8:8080
http://8.8.8.8:8080/page/to/deep#
http://some.test.yandex.ru

Негативные кейсы:
Проверку проходит следующий некорректный адреc сайта:
http://www.ya.
http://www (отсутствует доменная зона)
http://.ru (отсутствует доменное имя) 
http:something.ru (отсутствуют `//` после протокола) 
zzz://ya.ru (некорректный протокол. Допустимы только http\https)
http:\\google.ru
 httP://google.ru 
http://google.ru:/path/to/deep
https://999.999.999.999/ (у адреса ограничение: в ipv4 каждая часть адреса должна быть целым положительным числом и не больше 8 бит, те: 255)
http://something (отсутствует доменная зона)
http://1. (некорректный IP, точка на конце)
http://ya.ru:00000 (некорректный номер порта, в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными) 
http://127. (некорректный IP, точка на конце)
http://127.0..  (некорректный IP, точка на конце)
http://127.0.0.. (некорректный IP, точка на конце) 
http://127.0.0.1:8000/$ssss@# (некоректный путь - разрешены только цифры, слешы и латинские буквы, решетка (#) на конце) 
https://mysite.23 (tld не может состоять из цифр) 
http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1)
```

**Comment by zlocate** [comment]
Добрый вечер.
**Нужно исправить** Пожалуйста обратите внимание на комментарий перед тест-кейсами для адреса сайта. Там указано что не следует привязываться к конкретным доменам.
В текущей реализации у вас жестко заданы 2 доменны зоны .ru \ .com, cоответственно любой адрес сайта с иной доменной зоной не пройдет валидацию

**Comment by zlocate** [comment]
К сожалению, после правок поломались кейсы которые отрабатывали корректно раньше.


Проверку проходят следующие некорректные адреc сайта:
`http://www.ya.` - отсутствует доменная зона
`http://www` - отсутствует доменная зона
`http://.ru` - отсутствует доменное имя

З.Ы Я понимаю, что итерации доработок отнимают силы и демотивируют но не могу принять работу в которой кейсы отмеченные выше не обрабатываются.  :(

**Comment by aleksandrKrylov** [comment]
Да конечно, я понимаю. Хотел извиниться за свою не внимательность. Сейчас все проверил по всем тест-кейсам которые вы присылали, всё должно работать правильно. Спасибо вам за терпения.

**Comment by zlocate** [comment]
> Да конечно, я понимаю. Хотел извиниться за свою не внимательность. Сейчас все проверил по всем тест-кейсам которые вы присылали, всё должно работать правильно. Спасибо вам за терпения.

Не сочтите за критику. Просто коллеги-студенты очень на меня обижались когда кейсы повторно ломались :)

**Comment by zlocate** [comment]
Работа принята. Желаю вам успехов в дальнейшем обучении.
